[package]
name = "vorak-estacion"
version = "1.0.0"
description = "Estacion de pesaje VORAK"
authors = ["VORAK"]
edition = "2021"

[lib]
name = "vorak_estacion_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serialport = "4"
libc = "0.2"
image = "0.25"
imageproc = "0.25"
ab_glyph = "0.2"
chrono = { version = "0.4", features = ["clock"] }
tauri-plugin-localhost = "2"
