  # =====================================================================
  # Servicio para la Estación de Pesaje (Báscula Inteligente)
  # =====================================================================
services:
  estacion:
    container_name: vorak-estacion-edge
    image: ghcr.io/jumaar/estacion-vorak/estacion:${IMAGE_TAG:-latest} # <--- Comentado para desarrollo
    # --- MODO DE DESARROLLO LOCAL ---
    # build: .

    env_file:
      - ./.env
    network_mode: "host"

    volumes: # Permiten que el contenedor vea los eventos de hardware (conexión/desconexión) en tiempo real.
      - "/run/udev:/run/udev:ro"
      - "/sys:/sys:ro"
      - "/var/run/dbus:/var/run/dbus"
      - "/dev:/dev"

    privileged: true

    restart: unless-stopped